name: unpub_web
description: A web app that uses AngularDart Components
version: 1.0.0
publish_to: none
environment:
  # sdk: ">=2.3.0 <3.0.0"
  sdk: ^2.12.0
dependencies:
  angular: ^7.0.0
  angular_forms: ^4.0.0
  angular_router: ^3.0.0
  http: ^0.13.3
  markdown: 6.0.1
  unpub_api:
    path: ../unpub/lib/unpub_api
dev_dependencies:
  build_runner: ^2.1.11
  build_web_compilers: ^3.0.0